/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BankAccountDetails {
  'swiftBic' : string,
  'iban' : string,
  'accountHolderName' : string,
  'bankName' : string,
  'accountNumber' : string,
}
export interface Battery {
  'id' : string,
  'model' : string,
  'stock' : bigint,
  'warrantyMonths' : bigint,
  'brand' : string,
  'capacity' : bigint,
  'price' : bigint,
}
export interface BatteryPrice {
  'economyPrice' : number,
  'model' : string,
  'premiumPrice' : number,
  'premiumDiscount' : number,
  'standardPrice' : number,
  'economyDiscount' : number,
  'batterySize' : string,
  'batteryType' : string,
  'brand' : string,
  'standardDiscount' : number,
}
export interface Booking {
  'id' : string,
  'status' : BookingStatus,
  'serviceType' : ServiceType,
  'paymentStatus' : { 'pending' : null } |
    { 'paid' : null } |
    { 'failed' : null },
  'batteryId' : [] | [string],
  'customerPrincipal' : [] | [Principal],
  'technicianId' : [] | [string],
  'timestamp' : Time,
  'customerId' : string,
  'location' : Location,
}
export interface BookingInput {
  'serviceType' : ServiceType,
  'batteryId' : [] | [string],
  'customerId' : string,
  'location' : Location,
}
export type BookingStatus = { 'cancelled' : null } |
  { 'pending' : null } |
  { 'completed' : null } |
  { 'confirmed' : null } |
  { 'inProgress' : null };
export interface Customer {
  'id' : string,
  'name' : string,
  'email' : string,
  'address' : Location,
  'phone' : string,
  'serviceHistory' : Array<string>,
}
export interface FleetAccount {
  'id' : string,
  'vehicles' : Array<string>,
  'contactName' : string,
  'email' : string,
  'companyName' : string,
  'phone' : string,
  'serviceHistory' : Array<string>,
}
export interface Location {
  'latitude' : number,
  'city' : string,
  'longitude' : number,
  'address' : string,
  'emirate' : string,
}
export interface Notification {
  'to' : string,
  'method' : { 'sms' : null } |
    { 'whatsapp' : null } |
    { 'email' : null },
  'message' : string,
}
export type ServiceType = { 'fleetManagement' : null } |
  { 'jumpStart' : null } |
  { 'roadsideAssistance' : null } |
  { 'batteryReplacement' : null };
export interface ShoppingItem {
  'productName' : string,
  'currency' : string,
  'quantity' : bigint,
  'priceInCents' : bigint,
  'productDescription' : string,
}
export interface StoreLocation {
  'id' : string,
  'latitude' : number,
  'name' : string,
  'longitude' : number,
  'address' : string,
  'phone' : string,
}
export interface StripeConfiguration {
  'allowedCountries' : Array<string>,
  'secretKey' : string,
}
export type StripeSessionStatus = {
    'completed' : { 'userPrincipal' : [] | [string], 'response' : string }
  } |
  { 'failed' : { 'error' : string } };
export interface TechnicianProfile {
  'id' : string,
  'completedJobs' : bigint,
  'name' : string,
  'isActive' : boolean,
  'assignedJobs' : Array<string>,
  'phone' : string,
  'photo' : [] | [Uint8Array],
  'location' : Location,
}
export type Time = bigint;
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UserProfile {
  'userType' : { 'technician' : null } |
    { 'admin' : null } |
    { 'customer' : null },
  'name' : string,
  'email' : string,
  'technicianId' : [] | [string],
  'phone' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface Warranty {
  'id' : string,
  'batteryId' : string,
  'purchaseDate' : Time,
  'isActive' : boolean,
  'warrantyMonths' : bigint,
  'customerId' : string,
}
export interface WarrantyInput {
  'batteryId' : string,
  'purchaseDate' : Time,
  'warrantyMonths' : bigint,
  'customerId' : string,
}
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addBatteryPrice' : ActorMethod<[BatteryPrice], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'assignTechnician' : ActorMethod<[string, string], undefined>,
  'createBooking' : ActorMethod<[BookingInput], string>,
  'createCheckoutSession' : ActorMethod<
    [Array<ShoppingItem>, string, string],
    string
  >,
  'createCustomer' : ActorMethod<[Customer], undefined>,
  'createFleetAccount' : ActorMethod<[FleetAccount], undefined>,
  'createTechnician' : ActorMethod<[TechnicianProfile], undefined>,
  'createWarranty' : ActorMethod<[WarrantyInput], string>,
  'deleteBatteryInventory' : ActorMethod<[string], undefined>,
  'deleteBatteryPrice' : ActorMethod<[bigint], undefined>,
  'deleteTechnician' : ActorMethod<[string], undefined>,
  'findCompatibleBatteries' : ActorMethod<
    [string, string, bigint],
    Array<Battery>
  >,
  'getAllBatteryPrices' : ActorMethod<[string], Array<BatteryPrice>>,
  'getAllBookings' : ActorMethod<[], Array<Booking>>,
  'getAllCustomers' : ActorMethod<[], Array<Customer>>,
  'getAllFleetAccounts' : ActorMethod<[], Array<FleetAccount>>,
  'getAllWarranties' : ActorMethod<[], Array<Warranty>>,
  'getAvailableBatteries' : ActorMethod<[], Array<Battery>>,
  'getBookableTimeSlots' : ActorMethod<[], Array<string>>,
  'getBookingStatusCounts' : ActorMethod<[], Array<[BookingStatus, bigint]>>,
  'getBookingsByStatus' : ActorMethod<[BookingStatus], Array<Booking>>,
  'getBookingsByTechnician' : ActorMethod<[string], Array<Booking>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCustomer' : ActorMethod<[string], [] | [Customer]>,
  'getFilteredBatteryPrices' : ActorMethod<
    [
      [] | [string],
      [] | [string],
      [] | [string],
      [] | [string],
      [] | [[bigint, bigint]],
    ],
    Array<BatteryPrice>
  >,
  'getFleetAccount' : ActorMethod<[string], [] | [FleetAccount]>,
  'getMyBookings' : ActorMethod<[], Array<Booking>>,
  'getReceiverBankAccountDetails' : ActorMethod<[], BankAccountDetails>,
  'getReceiverIban' : ActorMethod<[], string>,
  'getServiceAreas' : ActorMethod<[], Array<string>>,
  'getStoreLocations' : ActorMethod<[], Array<StoreLocation>>,
  'getStripeSessionStatus' : ActorMethod<[string], StripeSessionStatus>,
  'getTechnicianAvailability' : ActorMethod<[], Array<TechnicianProfile>>,
  'getTechnicianLocation' : ActorMethod<[string], Location>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getWarranty' : ActorMethod<[string], [] | [Warranty]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isStripeConfigured' : ActorMethod<[], boolean>,
  'processPayment' : ActorMethod<[string, bigint, string, string], string>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'sendNotification' : ActorMethod<[Notification], undefined>,
  'setStripeConfiguration' : ActorMethod<[StripeConfiguration], undefined>,
  'testOutcall' : ActorMethod<[string], string>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateBatteryInventory' : ActorMethod<[Battery], undefined>,
  'updateBatteryPrice' : ActorMethod<[bigint, BatteryPrice], undefined>,
  'updateBookingStatus' : ActorMethod<[string, BookingStatus], undefined>,
  'updateReceiverBankAccountDetails' : ActorMethod<
    [BankAccountDetails],
    undefined
  >,
  'updateTechnician' : ActorMethod<[TechnicianProfile], undefined>,
  'updateTechnicianLocation' : ActorMethod<[string, Location], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];