/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const BatteryPrice = IDL.Record({
  'economyPrice' : IDL.Float64,
  'model' : IDL.Text,
  'premiumPrice' : IDL.Float64,
  'premiumDiscount' : IDL.Float64,
  'standardPrice' : IDL.Float64,
  'economyDiscount' : IDL.Float64,
  'batterySize' : IDL.Text,
  'batteryType' : IDL.Text,
  'brand' : IDL.Text,
  'standardDiscount' : IDL.Float64,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ServiceType = IDL.Variant({
  'fleetManagement' : IDL.Null,
  'jumpStart' : IDL.Null,
  'roadsideAssistance' : IDL.Null,
  'batteryReplacement' : IDL.Null,
});
export const Location = IDL.Record({
  'latitude' : IDL.Float64,
  'city' : IDL.Text,
  'longitude' : IDL.Float64,
  'address' : IDL.Text,
  'emirate' : IDL.Text,
});
export const BookingInput = IDL.Record({
  'serviceType' : ServiceType,
  'batteryId' : IDL.Opt(IDL.Text),
  'customerId' : IDL.Text,
  'location' : Location,
});
export const ShoppingItem = IDL.Record({
  'productName' : IDL.Text,
  'currency' : IDL.Text,
  'quantity' : IDL.Nat,
  'priceInCents' : IDL.Nat,
  'productDescription' : IDL.Text,
});
export const Customer = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'address' : Location,
  'phone' : IDL.Text,
  'serviceHistory' : IDL.Vec(IDL.Text),
});
export const FleetAccount = IDL.Record({
  'id' : IDL.Text,
  'vehicles' : IDL.Vec(IDL.Text),
  'contactName' : IDL.Text,
  'email' : IDL.Text,
  'companyName' : IDL.Text,
  'phone' : IDL.Text,
  'serviceHistory' : IDL.Vec(IDL.Text),
});
export const TechnicianProfile = IDL.Record({
  'id' : IDL.Text,
  'completedJobs' : IDL.Nat,
  'name' : IDL.Text,
  'isActive' : IDL.Bool,
  'assignedJobs' : IDL.Vec(IDL.Text),
  'phone' : IDL.Text,
  'photo' : IDL.Opt(IDL.Vec(IDL.Nat8)),
  'location' : Location,
});
export const Time = IDL.Int;
export const WarrantyInput = IDL.Record({
  'batteryId' : IDL.Text,
  'purchaseDate' : Time,
  'warrantyMonths' : IDL.Nat,
  'customerId' : IDL.Text,
});
export const Battery = IDL.Record({
  'id' : IDL.Text,
  'model' : IDL.Text,
  'stock' : IDL.Nat,
  'warrantyMonths' : IDL.Nat,
  'brand' : IDL.Text,
  'capacity' : IDL.Nat,
  'price' : IDL.Nat,
});
export const BookingStatus = IDL.Variant({
  'cancelled' : IDL.Null,
  'pending' : IDL.Null,
  'completed' : IDL.Null,
  'confirmed' : IDL.Null,
  'inProgress' : IDL.Null,
});
export const Booking = IDL.Record({
  'id' : IDL.Text,
  'status' : BookingStatus,
  'serviceType' : ServiceType,
  'paymentStatus' : IDL.Variant({
    'pending' : IDL.Null,
    'paid' : IDL.Null,
    'failed' : IDL.Null,
  }),
  'batteryId' : IDL.Opt(IDL.Text),
  'customerPrincipal' : IDL.Opt(IDL.Principal),
  'technicianId' : IDL.Opt(IDL.Text),
  'timestamp' : Time,
  'customerId' : IDL.Text,
  'location' : Location,
});
export const Warranty = IDL.Record({
  'id' : IDL.Text,
  'batteryId' : IDL.Text,
  'purchaseDate' : Time,
  'isActive' : IDL.Bool,
  'warrantyMonths' : IDL.Nat,
  'customerId' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'userType' : IDL.Variant({
    'technician' : IDL.Null,
    'admin' : IDL.Null,
    'customer' : IDL.Null,
  }),
  'name' : IDL.Text,
  'email' : IDL.Text,
  'technicianId' : IDL.Opt(IDL.Text),
  'phone' : IDL.Text,
});
export const BankAccountDetails = IDL.Record({
  'swiftBic' : IDL.Text,
  'iban' : IDL.Text,
  'accountHolderName' : IDL.Text,
  'bankName' : IDL.Text,
  'accountNumber' : IDL.Text,
});
export const StoreLocation = IDL.Record({
  'id' : IDL.Text,
  'latitude' : IDL.Float64,
  'name' : IDL.Text,
  'longitude' : IDL.Float64,
  'address' : IDL.Text,
  'phone' : IDL.Text,
});
export const StripeSessionStatus = IDL.Variant({
  'completed' : IDL.Record({
    'userPrincipal' : IDL.Opt(IDL.Text),
    'response' : IDL.Text,
  }),
  'failed' : IDL.Record({ 'error' : IDL.Text }),
});
export const Notification = IDL.Record({
  'to' : IDL.Text,
  'method' : IDL.Variant({
    'sms' : IDL.Null,
    'whatsapp' : IDL.Null,
    'email' : IDL.Null,
  }),
  'message' : IDL.Text,
});
export const StripeConfiguration = IDL.Record({
  'allowedCountries' : IDL.Vec(IDL.Text),
  'secretKey' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addBatteryPrice' : IDL.Func([BatteryPrice], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'assignTechnician' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'createBooking' : IDL.Func([BookingInput], [IDL.Text], []),
  'createCheckoutSession' : IDL.Func(
      [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'createCustomer' : IDL.Func([Customer], [], []),
  'createFleetAccount' : IDL.Func([FleetAccount], [], []),
  'createTechnician' : IDL.Func([TechnicianProfile], [], []),
  'createWarranty' : IDL.Func([WarrantyInput], [IDL.Text], []),
  'deleteBatteryInventory' : IDL.Func([IDL.Text], [], []),
  'deleteBatteryPrice' : IDL.Func([IDL.Nat], [], []),
  'deleteTechnician' : IDL.Func([IDL.Text], [], []),
  'findCompatibleBatteries' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat],
      [IDL.Vec(Battery)],
      ['query'],
    ),
  'getAllBatteryPrices' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(BatteryPrice)],
      ['query'],
    ),
  'getAllBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
  'getAllCustomers' : IDL.Func([], [IDL.Vec(Customer)], ['query']),
  'getAllFleetAccounts' : IDL.Func([], [IDL.Vec(FleetAccount)], ['query']),
  'getAllWarranties' : IDL.Func([], [IDL.Vec(Warranty)], ['query']),
  'getAvailableBatteries' : IDL.Func([], [IDL.Vec(Battery)], ['query']),
  'getBookableTimeSlots' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getBookingStatusCounts' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(BookingStatus, IDL.Nat))],
      ['query'],
    ),
  'getBookingsByStatus' : IDL.Func(
      [BookingStatus],
      [IDL.Vec(Booking)],
      ['query'],
    ),
  'getBookingsByTechnician' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(Booking)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCustomer' : IDL.Func([IDL.Text], [IDL.Opt(Customer)], ['query']),
  'getFilteredBatteryPrices' : IDL.Func(
      [
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Tuple(IDL.Nat, IDL.Nat)),
      ],
      [IDL.Vec(BatteryPrice)],
      ['query'],
    ),
  'getFleetAccount' : IDL.Func([IDL.Text], [IDL.Opt(FleetAccount)], ['query']),
  'getMyBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
  'getReceiverBankAccountDetails' : IDL.Func(
      [],
      [BankAccountDetails],
      ['query'],
    ),
  'getReceiverIban' : IDL.Func([], [IDL.Text], ['query']),
  'getServiceAreas' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getStoreLocations' : IDL.Func([], [IDL.Vec(StoreLocation)], ['query']),
  'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
  'getTechnicianAvailability' : IDL.Func(
      [],
      [IDL.Vec(TechnicianProfile)],
      ['query'],
    ),
  'getTechnicianLocation' : IDL.Func([IDL.Text], [Location], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getWarranty' : IDL.Func([IDL.Text], [IDL.Opt(Warranty)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
  'processPayment' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'sendNotification' : IDL.Func([Notification], [], []),
  'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
  'testOutcall' : IDL.Func([IDL.Text], [IDL.Text], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updateBatteryInventory' : IDL.Func([Battery], [], []),
  'updateBatteryPrice' : IDL.Func([IDL.Nat, BatteryPrice], [], []),
  'updateBookingStatus' : IDL.Func([IDL.Text, BookingStatus], [], []),
  'updateReceiverBankAccountDetails' : IDL.Func([BankAccountDetails], [], []),
  'updateTechnician' : IDL.Func([TechnicianProfile], [], []),
  'updateTechnicianLocation' : IDL.Func([IDL.Text, Location], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const BatteryPrice = IDL.Record({
    'economyPrice' : IDL.Float64,
    'model' : IDL.Text,
    'premiumPrice' : IDL.Float64,
    'premiumDiscount' : IDL.Float64,
    'standardPrice' : IDL.Float64,
    'economyDiscount' : IDL.Float64,
    'batterySize' : IDL.Text,
    'batteryType' : IDL.Text,
    'brand' : IDL.Text,
    'standardDiscount' : IDL.Float64,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ServiceType = IDL.Variant({
    'fleetManagement' : IDL.Null,
    'jumpStart' : IDL.Null,
    'roadsideAssistance' : IDL.Null,
    'batteryReplacement' : IDL.Null,
  });
  const Location = IDL.Record({
    'latitude' : IDL.Float64,
    'city' : IDL.Text,
    'longitude' : IDL.Float64,
    'address' : IDL.Text,
    'emirate' : IDL.Text,
  });
  const BookingInput = IDL.Record({
    'serviceType' : ServiceType,
    'batteryId' : IDL.Opt(IDL.Text),
    'customerId' : IDL.Text,
    'location' : Location,
  });
  const ShoppingItem = IDL.Record({
    'productName' : IDL.Text,
    'currency' : IDL.Text,
    'quantity' : IDL.Nat,
    'priceInCents' : IDL.Nat,
    'productDescription' : IDL.Text,
  });
  const Customer = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'address' : Location,
    'phone' : IDL.Text,
    'serviceHistory' : IDL.Vec(IDL.Text),
  });
  const FleetAccount = IDL.Record({
    'id' : IDL.Text,
    'vehicles' : IDL.Vec(IDL.Text),
    'contactName' : IDL.Text,
    'email' : IDL.Text,
    'companyName' : IDL.Text,
    'phone' : IDL.Text,
    'serviceHistory' : IDL.Vec(IDL.Text),
  });
  const TechnicianProfile = IDL.Record({
    'id' : IDL.Text,
    'completedJobs' : IDL.Nat,
    'name' : IDL.Text,
    'isActive' : IDL.Bool,
    'assignedJobs' : IDL.Vec(IDL.Text),
    'phone' : IDL.Text,
    'photo' : IDL.Opt(IDL.Vec(IDL.Nat8)),
    'location' : Location,
  });
  const Time = IDL.Int;
  const WarrantyInput = IDL.Record({
    'batteryId' : IDL.Text,
    'purchaseDate' : Time,
    'warrantyMonths' : IDL.Nat,
    'customerId' : IDL.Text,
  });
  const Battery = IDL.Record({
    'id' : IDL.Text,
    'model' : IDL.Text,
    'stock' : IDL.Nat,
    'warrantyMonths' : IDL.Nat,
    'brand' : IDL.Text,
    'capacity' : IDL.Nat,
    'price' : IDL.Nat,
  });
  const BookingStatus = IDL.Variant({
    'cancelled' : IDL.Null,
    'pending' : IDL.Null,
    'completed' : IDL.Null,
    'confirmed' : IDL.Null,
    'inProgress' : IDL.Null,
  });
  const Booking = IDL.Record({
    'id' : IDL.Text,
    'status' : BookingStatus,
    'serviceType' : ServiceType,
    'paymentStatus' : IDL.Variant({
      'pending' : IDL.Null,
      'paid' : IDL.Null,
      'failed' : IDL.Null,
    }),
    'batteryId' : IDL.Opt(IDL.Text),
    'customerPrincipal' : IDL.Opt(IDL.Principal),
    'technicianId' : IDL.Opt(IDL.Text),
    'timestamp' : Time,
    'customerId' : IDL.Text,
    'location' : Location,
  });
  const Warranty = IDL.Record({
    'id' : IDL.Text,
    'batteryId' : IDL.Text,
    'purchaseDate' : Time,
    'isActive' : IDL.Bool,
    'warrantyMonths' : IDL.Nat,
    'customerId' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'userType' : IDL.Variant({
      'technician' : IDL.Null,
      'admin' : IDL.Null,
      'customer' : IDL.Null,
    }),
    'name' : IDL.Text,
    'email' : IDL.Text,
    'technicianId' : IDL.Opt(IDL.Text),
    'phone' : IDL.Text,
  });
  const BankAccountDetails = IDL.Record({
    'swiftBic' : IDL.Text,
    'iban' : IDL.Text,
    'accountHolderName' : IDL.Text,
    'bankName' : IDL.Text,
    'accountNumber' : IDL.Text,
  });
  const StoreLocation = IDL.Record({
    'id' : IDL.Text,
    'latitude' : IDL.Float64,
    'name' : IDL.Text,
    'longitude' : IDL.Float64,
    'address' : IDL.Text,
    'phone' : IDL.Text,
  });
  const StripeSessionStatus = IDL.Variant({
    'completed' : IDL.Record({
      'userPrincipal' : IDL.Opt(IDL.Text),
      'response' : IDL.Text,
    }),
    'failed' : IDL.Record({ 'error' : IDL.Text }),
  });
  const Notification = IDL.Record({
    'to' : IDL.Text,
    'method' : IDL.Variant({
      'sms' : IDL.Null,
      'whatsapp' : IDL.Null,
      'email' : IDL.Null,
    }),
    'message' : IDL.Text,
  });
  const StripeConfiguration = IDL.Record({
    'allowedCountries' : IDL.Vec(IDL.Text),
    'secretKey' : IDL.Text,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addBatteryPrice' : IDL.Func([BatteryPrice], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'assignTechnician' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'createBooking' : IDL.Func([BookingInput], [IDL.Text], []),
    'createCheckoutSession' : IDL.Func(
        [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'createCustomer' : IDL.Func([Customer], [], []),
    'createFleetAccount' : IDL.Func([FleetAccount], [], []),
    'createTechnician' : IDL.Func([TechnicianProfile], [], []),
    'createWarranty' : IDL.Func([WarrantyInput], [IDL.Text], []),
    'deleteBatteryInventory' : IDL.Func([IDL.Text], [], []),
    'deleteBatteryPrice' : IDL.Func([IDL.Nat], [], []),
    'deleteTechnician' : IDL.Func([IDL.Text], [], []),
    'findCompatibleBatteries' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat],
        [IDL.Vec(Battery)],
        ['query'],
      ),
    'getAllBatteryPrices' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(BatteryPrice)],
        ['query'],
      ),
    'getAllBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
    'getAllCustomers' : IDL.Func([], [IDL.Vec(Customer)], ['query']),
    'getAllFleetAccounts' : IDL.Func([], [IDL.Vec(FleetAccount)], ['query']),
    'getAllWarranties' : IDL.Func([], [IDL.Vec(Warranty)], ['query']),
    'getAvailableBatteries' : IDL.Func([], [IDL.Vec(Battery)], ['query']),
    'getBookableTimeSlots' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getBookingStatusCounts' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(BookingStatus, IDL.Nat))],
        ['query'],
      ),
    'getBookingsByStatus' : IDL.Func(
        [BookingStatus],
        [IDL.Vec(Booking)],
        ['query'],
      ),
    'getBookingsByTechnician' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Booking)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCustomer' : IDL.Func([IDL.Text], [IDL.Opt(Customer)], ['query']),
    'getFilteredBatteryPrices' : IDL.Func(
        [
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Tuple(IDL.Nat, IDL.Nat)),
        ],
        [IDL.Vec(BatteryPrice)],
        ['query'],
      ),
    'getFleetAccount' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(FleetAccount)],
        ['query'],
      ),
    'getMyBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
    'getReceiverBankAccountDetails' : IDL.Func(
        [],
        [BankAccountDetails],
        ['query'],
      ),
    'getReceiverIban' : IDL.Func([], [IDL.Text], ['query']),
    'getServiceAreas' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getStoreLocations' : IDL.Func([], [IDL.Vec(StoreLocation)], ['query']),
    'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
    'getTechnicianAvailability' : IDL.Func(
        [],
        [IDL.Vec(TechnicianProfile)],
        ['query'],
      ),
    'getTechnicianLocation' : IDL.Func([IDL.Text], [Location], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getWarranty' : IDL.Func([IDL.Text], [IDL.Opt(Warranty)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
    'processPayment' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'sendNotification' : IDL.Func([Notification], [], []),
    'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
    'testOutcall' : IDL.Func([IDL.Text], [IDL.Text], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updateBatteryInventory' : IDL.Func([Battery], [], []),
    'updateBatteryPrice' : IDL.Func([IDL.Nat, BatteryPrice], [], []),
    'updateBookingStatus' : IDL.Func([IDL.Text, BookingStatus], [], []),
    'updateReceiverBankAccountDetails' : IDL.Func([BankAccountDetails], [], []),
    'updateTechnician' : IDL.Func([TechnicianProfile], [], []),
    'updateTechnicianLocation' : IDL.Func([IDL.Text, Location], [], []),
  });
};

export const init = ({ IDL }) => { return []; };