/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Location {
    latitude: number;
    city: string;
    longitude: number;
    address: string;
    emirate: string;
}
export interface BatteryPrice {
    economyPrice: number;
    model: string;
    premiumPrice: number;
    premiumDiscount: number;
    standardPrice: number;
    economyDiscount: number;
    batterySize: string;
    batteryType: string;
    brand: string;
    standardDiscount: number;
}
export interface TransformationOutput {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export type Time = bigint;
export interface StoreLocation {
    id: string;
    latitude: number;
    name: string;
    longitude: number;
    address: string;
    phone: string;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface BookingInput {
    serviceType: ServiceType;
    batteryId?: string;
    customerId: string;
    location: Location;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface Battery {
    id: string;
    model: string;
    stock: bigint;
    warrantyMonths: bigint;
    brand: string;
    capacity: bigint;
    price: bigint;
}
export interface Customer {
    id: string;
    name: string;
    email: string;
    address: Location;
    phone: string;
    serviceHistory: Array<string>;
}
export interface http_header {
    value: string;
    name: string;
}
export interface http_request_result {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface WarrantyInput {
    batteryId: string;
    purchaseDate: Time;
    warrantyMonths: bigint;
    customerId: string;
}
export interface FleetAccount {
    id: string;
    vehicles: Array<string>;
    contactName: string;
    email: string;
    companyName: string;
    phone: string;
    serviceHistory: Array<string>;
}
export interface ShoppingItem {
    productName: string;
    currency: string;
    quantity: bigint;
    priceInCents: bigint;
    productDescription: string;
}
export interface Warranty {
    id: string;
    batteryId: string;
    purchaseDate: Time;
    isActive: boolean;
    warrantyMonths: bigint;
    customerId: string;
}
export interface TechnicianProfile {
    id: string;
    completedJobs: bigint;
    name: string;
    isActive: boolean;
    assignedJobs: Array<string>;
    phone: string;
    photo?: Uint8Array;
    location: Location;
}
export interface TransformationInput {
    context: Uint8Array;
    response: http_request_result;
}
export interface Notification {
    to: string;
    method: Variant_sms_whatsapp_email;
    message: string;
}
export interface Booking {
    id: string;
    status: BookingStatus;
    serviceType: ServiceType;
    paymentStatus: Variant_pending_paid_failed;
    batteryId?: string;
    customerPrincipal?: Principal;
    technicianId?: string;
    timestamp: Time;
    customerId: string;
    location: Location;
}
export type StripeSessionStatus = {
    __kind__: "completed";
    completed: {
        userPrincipal?: string;
        response: string;
    };
} | {
    __kind__: "failed";
    failed: {
        error: string;
    };
};
export interface StripeConfiguration {
    allowedCountries: Array<string>;
    secretKey: string;
}
export interface UserProfile {
    userType: Variant_technician_admin_customer;
    name: string;
    email: string;
    technicianId?: string;
    phone: string;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export enum BookingStatus {
    cancelled = "cancelled",
    pending = "pending",
    completed = "completed",
    confirmed = "confirmed",
    inProgress = "inProgress"
}
export enum ServiceType {
    fleetManagement = "fleetManagement",
    jumpStart = "jumpStart",
    roadsideAssistance = "roadsideAssistance",
    batteryReplacement = "batteryReplacement"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum Variant_pending_paid_failed {
    pending = "pending",
    paid = "paid",
    failed = "failed"
}
export enum Variant_sms_whatsapp_email {
    sms = "sms",
    whatsapp = "whatsapp",
    email = "email"
}
export enum Variant_technician_admin_customer {
    technician = "technician",
    admin = "admin",
    customer = "customer"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addBatteryPrice(price: BatteryPrice): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    assignTechnician(bookingId: string, techId: string): Promise<void>;
    createBooking(input: BookingInput): Promise<string>;
    createCheckoutSession(items: Array<ShoppingItem>, successUrl: string, cancelUrl: string): Promise<string>;
    createCustomer(customer: Customer): Promise<void>;
    createFleetAccount(fleet: FleetAccount): Promise<void>;
    createTechnician(profile: TechnicianProfile): Promise<void>;
    createWarranty(input: WarrantyInput): Promise<string>;
    deleteBatteryInventory(batteryId: string): Promise<void>;
    deleteBatteryPrice(index: bigint): Promise<void>;
    deleteTechnician(techId: string): Promise<void>;
    findCompatibleBatteries(make: string, model: string, year: bigint): Promise<Array<Battery>>;
    getAllBatteryPrices(sortBy: string): Promise<Array<BatteryPrice>>;
    getAllBookings(): Promise<Array<Booking>>;
    getAllCustomers(): Promise<Array<Customer>>;
    getAllFleetAccounts(): Promise<Array<FleetAccount>>;
    getAllWarranties(): Promise<Array<Warranty>>;
    getAvailableBatteries(): Promise<Array<Battery>>;
    getBookableTimeSlots(): Promise<Array<string>>;
    getBookingStatusCounts(): Promise<Array<[BookingStatus, bigint]>>;
    getBookingsByStatus(status: BookingStatus): Promise<Array<Booking>>;
    getBookingsByTechnician(techId: string): Promise<Array<Booking>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCustomer(customerId: string): Promise<Customer | null>;
    getFilteredBatteryPrices(brand: string | null, model: string | null, batteryType: string | null, batterySize: string | null, priceRange: [bigint, bigint] | null): Promise<Array<BatteryPrice>>;
    getFleetAccount(fleetId: string): Promise<FleetAccount | null>;
    getMyBookings(): Promise<Array<Booking>>;
    getServiceAreas(): Promise<Array<string>>;
    getStoreLocations(): Promise<Array<StoreLocation>>;
    getStripeSessionStatus(sessionId: string): Promise<StripeSessionStatus>;
    getTechnicianAvailability(): Promise<Array<TechnicianProfile>>;
    getTechnicianLocation(techId: string): Promise<Location>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    getWarranty(warrantyId: string): Promise<Warranty | null>;
    isCallerAdmin(): Promise<boolean>;
    isStripeConfigured(): Promise<boolean>;
    processPayment(bookingId: string, amount: bigint, currency: string, method: string): Promise<string>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    sendNotification(notification: Notification): Promise<void>;
    setStripeConfiguration(config: StripeConfiguration): Promise<void>;
    testOutcall(arg0: string): Promise<string>;
    transform(input: TransformationInput): Promise<TransformationOutput>;
    updateBatteryInventory(battery: Battery): Promise<void>;
    updateBatteryPrice(index: bigint, price: BatteryPrice): Promise<void>;
    updateBookingStatus(bookingId: string, newStatus: BookingStatus): Promise<void>;
    updateTechnician(profile: TechnicianProfile): Promise<void>;
    updateTechnicianLocation(techId: string, newLocation: Location): Promise<void>;
}
import type { Booking as _Booking, BookingInput as _BookingInput, BookingStatus as _BookingStatus, Customer as _Customer, FleetAccount as _FleetAccount, Location as _Location, Notification as _Notification, ServiceType as _ServiceType, StripeSessionStatus as _StripeSessionStatus, TechnicianProfile as _TechnicianProfile, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole, Warranty as _Warranty, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addBatteryPrice(arg0: BatteryPrice): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addBatteryPrice(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addBatteryPrice(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async assignTechnician(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignTechnician(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignTechnician(arg0, arg1);
            return result;
        }
    }
    async createBooking(arg0: BookingInput): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createBooking(to_candid_BookingInput_n10(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createBooking(to_candid_BookingInput_n10(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async createCheckoutSession(arg0: Array<ShoppingItem>, arg1: string, arg2: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createCheckoutSession(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCheckoutSession(arg0, arg1, arg2);
            return result;
        }
    }
    async createCustomer(arg0: Customer): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createCustomer(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCustomer(arg0);
            return result;
        }
    }
    async createFleetAccount(arg0: FleetAccount): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createFleetAccount(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createFleetAccount(arg0);
            return result;
        }
    }
    async createTechnician(arg0: TechnicianProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createTechnician(to_candid_TechnicianProfile_n14(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createTechnician(to_candid_TechnicianProfile_n14(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async createWarranty(arg0: WarrantyInput): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createWarranty(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createWarranty(arg0);
            return result;
        }
    }
    async deleteBatteryInventory(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteBatteryInventory(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteBatteryInventory(arg0);
            return result;
        }
    }
    async deleteBatteryPrice(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteBatteryPrice(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteBatteryPrice(arg0);
            return result;
        }
    }
    async deleteTechnician(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteTechnician(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteTechnician(arg0);
            return result;
        }
    }
    async findCompatibleBatteries(arg0: string, arg1: string, arg2: bigint): Promise<Array<Battery>> {
        if (this.processError) {
            try {
                const result = await this.actor.findCompatibleBatteries(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.findCompatibleBatteries(arg0, arg1, arg2);
            return result;
        }
    }
    async getAllBatteryPrices(arg0: string): Promise<Array<BatteryPrice>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllBatteryPrices(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllBatteryPrices(arg0);
            return result;
        }
    }
    async getAllBookings(): Promise<Array<Booking>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllBookings();
                return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllBookings();
            return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllCustomers(): Promise<Array<Customer>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllCustomers();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllCustomers();
            return result;
        }
    }
    async getAllFleetAccounts(): Promise<Array<FleetAccount>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllFleetAccounts();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllFleetAccounts();
            return result;
        }
    }
    async getAllWarranties(): Promise<Array<Warranty>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllWarranties();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllWarranties();
            return result;
        }
    }
    async getAvailableBatteries(): Promise<Array<Battery>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAvailableBatteries();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAvailableBatteries();
            return result;
        }
    }
    async getBookableTimeSlots(): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBookableTimeSlots();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBookableTimeSlots();
            return result;
        }
    }
    async getBookingStatusCounts(): Promise<Array<[BookingStatus, bigint]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBookingStatusCounts();
                return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBookingStatusCounts();
            return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBookingsByStatus(arg0: BookingStatus): Promise<Array<Booking>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBookingsByStatus(to_candid_BookingStatus_n28(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBookingsByStatus(to_candid_BookingStatus_n28(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBookingsByTechnician(arg0: string): Promise<Array<Booking>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBookingsByTechnician(arg0);
                return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBookingsByTechnician(arg0);
            return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCustomer(arg0: string): Promise<Customer | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCustomer(arg0);
                return from_candid_opt_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCustomer(arg0);
            return from_candid_opt_n36(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFilteredBatteryPrices(arg0: string | null, arg1: string | null, arg2: string | null, arg3: string | null, arg4: [bigint, bigint] | null): Promise<Array<BatteryPrice>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFilteredBatteryPrices(to_candid_opt_n37(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n37(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n37(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n37(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n38(this._uploadFile, this._downloadFile, arg4));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFilteredBatteryPrices(to_candid_opt_n37(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n37(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n37(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n37(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n38(this._uploadFile, this._downloadFile, arg4));
            return result;
        }
    }
    async getFleetAccount(arg0: string): Promise<FleetAccount | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getFleetAccount(arg0);
                return from_candid_opt_n39(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFleetAccount(arg0);
            return from_candid_opt_n39(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyBookings(): Promise<Array<Booking>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyBookings();
                return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyBookings();
            return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getServiceAreas(): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.getServiceAreas();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getServiceAreas();
            return result;
        }
    }
    async getStoreLocations(): Promise<Array<StoreLocation>> {
        if (this.processError) {
            try {
                const result = await this.actor.getStoreLocations();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStoreLocations();
            return result;
        }
    }
    async getStripeSessionStatus(arg0: string): Promise<StripeSessionStatus> {
        if (this.processError) {
            try {
                const result = await this.actor.getStripeSessionStatus(arg0);
                return from_candid_StripeSessionStatus_n40(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStripeSessionStatus(arg0);
            return from_candid_StripeSessionStatus_n40(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTechnicianAvailability(): Promise<Array<TechnicianProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTechnicianAvailability();
                return from_candid_vec_n43(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTechnicianAvailability();
            return from_candid_vec_n43(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTechnicianLocation(arg0: string): Promise<Location> {
        if (this.processError) {
            try {
                const result = await this.actor.getTechnicianLocation(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTechnicianLocation(arg0);
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getWarranty(arg0: string): Promise<Warranty | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getWarranty(arg0);
                return from_candid_opt_n47(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWarranty(arg0);
            return from_candid_opt_n47(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async isStripeConfigured(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isStripeConfigured();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isStripeConfigured();
            return result;
        }
    }
    async processPayment(arg0: string, arg1: bigint, arg2: string, arg3: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.processPayment(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.processPayment(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n48(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n48(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async sendNotification(arg0: Notification): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.sendNotification(to_candid_Notification_n51(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendNotification(to_candid_Notification_n51(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async setStripeConfiguration(arg0: StripeConfiguration): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setStripeConfiguration(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setStripeConfiguration(arg0);
            return result;
        }
    }
    async testOutcall(arg0: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.testOutcall(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.testOutcall(arg0);
            return result;
        }
    }
    async transform(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.transform(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transform(arg0);
            return result;
        }
    }
    async updateBatteryInventory(arg0: Battery): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateBatteryInventory(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateBatteryInventory(arg0);
            return result;
        }
    }
    async updateBatteryPrice(arg0: bigint, arg1: BatteryPrice): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateBatteryPrice(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateBatteryPrice(arg0, arg1);
            return result;
        }
    }
    async updateBookingStatus(arg0: string, arg1: BookingStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateBookingStatus(arg0, to_candid_BookingStatus_n28(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateBookingStatus(arg0, to_candid_BookingStatus_n28(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateTechnician(arg0: TechnicianProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTechnician(to_candid_TechnicianProfile_n14(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTechnician(to_candid_TechnicianProfile_n14(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateTechnicianLocation(arg0: string, arg1: Location): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTechnicianLocation(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTechnicianLocation(arg0, arg1);
            return result;
        }
    }
}
function from_candid_BookingStatus_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BookingStatus): BookingStatus {
    return from_candid_variant_n20(_uploadFile, _downloadFile, value);
}
function from_candid_Booking_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Booking): Booking {
    return from_candid_record_n18(_uploadFile, _downloadFile, value);
}
function from_candid_ServiceType_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ServiceType): ServiceType {
    return from_candid_variant_n22(_uploadFile, _downloadFile, value);
}
function from_candid_StripeSessionStatus_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StripeSessionStatus): StripeSessionStatus {
    return from_candid_variant_n41(_uploadFile, _downloadFile, value);
}
function from_candid_TechnicianProfile_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TechnicianProfile): TechnicianProfile {
    return from_candid_record_n45(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n32(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n35(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Principal]): Principal | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n31(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Customer]): Customer | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_FleetAccount]): FleetAccount | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Uint8Array]): Uint8Array | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Warranty]): Warranty | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: _BookingStatus;
    serviceType: _ServiceType;
    paymentStatus: {
        pending: null;
    } | {
        paid: null;
    } | {
        failed: null;
    };
    batteryId: [] | [string];
    customerPrincipal: [] | [Principal];
    technicianId: [] | [string];
    timestamp: _Time;
    customerId: string;
    location: _Location;
}): {
    id: string;
    status: BookingStatus;
    serviceType: ServiceType;
    paymentStatus: Variant_pending_paid_failed;
    batteryId?: string;
    customerPrincipal?: Principal;
    technicianId?: string;
    timestamp: Time;
    customerId: string;
    location: Location;
} {
    return {
        id: value.id,
        status: from_candid_BookingStatus_n19(_uploadFile, _downloadFile, value.status),
        serviceType: from_candid_ServiceType_n21(_uploadFile, _downloadFile, value.serviceType),
        paymentStatus: from_candid_variant_n23(_uploadFile, _downloadFile, value.paymentStatus),
        batteryId: record_opt_to_undefined(from_candid_opt_n24(_uploadFile, _downloadFile, value.batteryId)),
        customerPrincipal: record_opt_to_undefined(from_candid_opt_n25(_uploadFile, _downloadFile, value.customerPrincipal)),
        technicianId: record_opt_to_undefined(from_candid_opt_n24(_uploadFile, _downloadFile, value.technicianId)),
        timestamp: value.timestamp,
        customerId: value.customerId,
        location: value.location
    };
}
function from_candid_record_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    userType: {
        technician: null;
    } | {
        admin: null;
    } | {
        customer: null;
    };
    name: string;
    email: string;
    technicianId: [] | [string];
    phone: string;
}): {
    userType: Variant_technician_admin_customer;
    name: string;
    email: string;
    technicianId?: string;
    phone: string;
} {
    return {
        userType: from_candid_variant_n33(_uploadFile, _downloadFile, value.userType),
        name: value.name,
        email: value.email,
        technicianId: record_opt_to_undefined(from_candid_opt_n24(_uploadFile, _downloadFile, value.technicianId)),
        phone: value.phone
    };
}
function from_candid_record_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    userPrincipal: [] | [string];
    response: string;
}): {
    userPrincipal?: string;
    response: string;
} {
    return {
        userPrincipal: record_opt_to_undefined(from_candid_opt_n24(_uploadFile, _downloadFile, value.userPrincipal)),
        response: value.response
    };
}
function from_candid_record_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    completedJobs: bigint;
    name: string;
    isActive: boolean;
    assignedJobs: Array<string>;
    phone: string;
    photo: [] | [Uint8Array];
    location: _Location;
}): {
    id: string;
    completedJobs: bigint;
    name: string;
    isActive: boolean;
    assignedJobs: Array<string>;
    phone: string;
    photo?: Uint8Array;
    location: Location;
} {
    return {
        id: value.id,
        completedJobs: value.completedJobs,
        name: value.name,
        isActive: value.isActive,
        assignedJobs: value.assignedJobs,
        phone: value.phone,
        photo: record_opt_to_undefined(from_candid_opt_n46(_uploadFile, _downloadFile, value.photo)),
        location: value.location
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_tuple_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [_BookingStatus, bigint]): [BookingStatus, bigint] {
    return [
        from_candid_BookingStatus_n19(_uploadFile, _downloadFile, value[0]),
        value[1]
    ];
}
function from_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    cancelled: null;
} | {
    pending: null;
} | {
    completed: null;
} | {
    confirmed: null;
} | {
    inProgress: null;
}): BookingStatus {
    return "cancelled" in value ? BookingStatus.cancelled : "pending" in value ? BookingStatus.pending : "completed" in value ? BookingStatus.completed : "confirmed" in value ? BookingStatus.confirmed : "inProgress" in value ? BookingStatus.inProgress : value;
}
function from_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    fleetManagement: null;
} | {
    jumpStart: null;
} | {
    roadsideAssistance: null;
} | {
    batteryReplacement: null;
}): ServiceType {
    return "fleetManagement" in value ? ServiceType.fleetManagement : "jumpStart" in value ? ServiceType.jumpStart : "roadsideAssistance" in value ? ServiceType.roadsideAssistance : "batteryReplacement" in value ? ServiceType.batteryReplacement : value;
}
function from_candid_variant_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    paid: null;
} | {
    failed: null;
}): Variant_pending_paid_failed {
    return "pending" in value ? Variant_pending_paid_failed.pending : "paid" in value ? Variant_pending_paid_failed.paid : "failed" in value ? Variant_pending_paid_failed.failed : value;
}
function from_candid_variant_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    technician: null;
} | {
    admin: null;
} | {
    customer: null;
}): Variant_technician_admin_customer {
    return "technician" in value ? Variant_technician_admin_customer.technician : "admin" in value ? Variant_technician_admin_customer.admin : "customer" in value ? Variant_technician_admin_customer.customer : value;
}
function from_candid_variant_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    completed: {
        userPrincipal: [] | [string];
        response: string;
    };
} | {
    failed: {
        error: string;
    };
}): {
    __kind__: "completed";
    completed: {
        userPrincipal?: string;
        response: string;
    };
} | {
    __kind__: "failed";
    failed: {
        error: string;
    };
} {
    return "completed" in value ? {
        __kind__: "completed",
        completed: from_candid_record_n42(_uploadFile, _downloadFile, value.completed)
    } : "failed" in value ? {
        __kind__: "failed",
        failed: value.failed
    } : value;
}
function from_candid_vec_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Booking>): Array<Booking> {
    return value.map((x)=>from_candid_Booking_n17(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[_BookingStatus, bigint]>): Array<[BookingStatus, bigint]> {
    return value.map((x)=>from_candid_tuple_n27(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_TechnicianProfile>): Array<TechnicianProfile> {
    return value.map((x)=>from_candid_TechnicianProfile_n44(_uploadFile, _downloadFile, x));
}
function to_candid_BookingInput_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BookingInput): _BookingInput {
    return to_candid_record_n11(_uploadFile, _downloadFile, value);
}
function to_candid_BookingStatus_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BookingStatus): _BookingStatus {
    return to_candid_variant_n29(_uploadFile, _downloadFile, value);
}
function to_candid_Notification_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Notification): _Notification {
    return to_candid_record_n52(_uploadFile, _downloadFile, value);
}
function to_candid_ServiceType_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ServiceType): _ServiceType {
    return to_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function to_candid_TechnicianProfile_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TechnicianProfile): _TechnicianProfile {
    return to_candid_record_n15(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n49(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [bigint, bigint] | null): [] | [[bigint, bigint]] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    serviceType: ServiceType;
    batteryId?: string;
    customerId: string;
    location: Location;
}): {
    serviceType: _ServiceType;
    batteryId: [] | [string];
    customerId: string;
    location: _Location;
} {
    return {
        serviceType: to_candid_ServiceType_n12(_uploadFile, _downloadFile, value.serviceType),
        batteryId: value.batteryId ? candid_some(value.batteryId) : candid_none(),
        customerId: value.customerId,
        location: value.location
    };
}
function to_candid_record_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    completedJobs: bigint;
    name: string;
    isActive: boolean;
    assignedJobs: Array<string>;
    phone: string;
    photo?: Uint8Array;
    location: Location;
}): {
    id: string;
    completedJobs: bigint;
    name: string;
    isActive: boolean;
    assignedJobs: Array<string>;
    phone: string;
    photo: [] | [Uint8Array];
    location: _Location;
} {
    return {
        id: value.id,
        completedJobs: value.completedJobs,
        name: value.name,
        isActive: value.isActive,
        assignedJobs: value.assignedJobs,
        phone: value.phone,
        photo: value.photo ? candid_some(value.photo) : candid_none(),
        location: value.location
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    userType: Variant_technician_admin_customer;
    name: string;
    email: string;
    technicianId?: string;
    phone: string;
}): {
    userType: {
        technician: null;
    } | {
        admin: null;
    } | {
        customer: null;
    };
    name: string;
    email: string;
    technicianId: [] | [string];
    phone: string;
} {
    return {
        userType: to_candid_variant_n50(_uploadFile, _downloadFile, value.userType),
        name: value.name,
        email: value.email,
        technicianId: value.technicianId ? candid_some(value.technicianId) : candid_none(),
        phone: value.phone
    };
}
function to_candid_record_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    to: string;
    method: Variant_sms_whatsapp_email;
    message: string;
}): {
    to: string;
    method: {
        sms: null;
    } | {
        whatsapp: null;
    } | {
        email: null;
    };
    message: string;
} {
    return {
        to: value.to,
        method: to_candid_variant_n53(_uploadFile, _downloadFile, value.method),
        message: value.message
    };
}
function to_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ServiceType): {
    fleetManagement: null;
} | {
    jumpStart: null;
} | {
    roadsideAssistance: null;
} | {
    batteryReplacement: null;
} {
    return value == ServiceType.fleetManagement ? {
        fleetManagement: null
    } : value == ServiceType.jumpStart ? {
        jumpStart: null
    } : value == ServiceType.roadsideAssistance ? {
        roadsideAssistance: null
    } : value == ServiceType.batteryReplacement ? {
        batteryReplacement: null
    } : value;
}
function to_candid_variant_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BookingStatus): {
    cancelled: null;
} | {
    pending: null;
} | {
    completed: null;
} | {
    confirmed: null;
} | {
    inProgress: null;
} {
    return value == BookingStatus.cancelled ? {
        cancelled: null
    } : value == BookingStatus.pending ? {
        pending: null
    } : value == BookingStatus.completed ? {
        completed: null
    } : value == BookingStatus.confirmed ? {
        confirmed: null
    } : value == BookingStatus.inProgress ? {
        inProgress: null
    } : value;
}
function to_candid_variant_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_technician_admin_customer): {
    technician: null;
} | {
    admin: null;
} | {
    customer: null;
} {
    return value == Variant_technician_admin_customer.technician ? {
        technician: null
    } : value == Variant_technician_admin_customer.admin ? {
        admin: null
    } : value == Variant_technician_admin_customer.customer ? {
        customer: null
    } : value;
}
function to_candid_variant_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_sms_whatsapp_email): {
    sms: null;
} | {
    whatsapp: null;
} | {
    email: null;
} {
    return value == Variant_sms_whatsapp_email.sms ? {
        sms: null
    } : value == Variant_sms_whatsapp_email.whatsapp ? {
        whatsapp: null
    } : value == Variant_sms_whatsapp_email.email ? {
        email: null
    } : value;
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
